#!/usr/bin/with-contenv bash

USER_NAME=${USER_NAME:-linuxserver.io}

exec 2>&1 \
        s6-setuidgid ${USER_NAME} /usr/sbin/sshd -D -e -p 22

# port forward service
exec 2>&1 \
        s6-setuidgid ${USER_NAME} /usr/bin/ssh -f -N -D 1080 localhost
