name: explore

on:
  push:
    paths:
      - 'explore.Dockerfile'

  workflow_dispatch:
#  pull_request:
#    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v1
     - name: Login to DockerHub Registry
       run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
     - name: Build the latest Docker image
       run: docker build . --file explore.Dockerfile --tag mattlu/explore-dev:latest
     - name: Push the latest Docker image
       run: docker push mattlu/explore-dev:latest
