name: socks-node-self

on:
  push:
    paths:
      - 'socks-node-self.Dockerfile'
      - 'scripts/socks-node-self.sh'

  workflow_dispatch:
#  pull_request:
#    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v1
     - name: Login to DockerHub Registry
       run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
     - name: Build the latest Docker image
       run: |
         docker build . --file socks-node-self.Dockerfile --tag socks-node-self
         docker image tag socks-node-self mattlu/socks-node-self:latest

     - name: Push the latest Docker image
       run: docker push --all-tags mattlu/socks-node-self
