name: wireguard

on:
  push:
    paths:
      - 'wireguard.Dockerfile'
      - 'scripts/wireguard.sh'

  workflow_dispatch:
#  pull_request:
#    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v1
     - name: Login to DockerHub Registry
       run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
     - name: Build the latest Wireguard image
       run: |
         docker build . --file wireguard.Dockerfile --tag wireguard
         docker image tag wireguard mattlu/wireguard:latest

     - name: Push the latest Wireguard image
       run: docker push --all-tags mattlu/wireguard
