name: work-dev-18.04

on:
  push:
    paths:
      - 'work.Dockerfile'

  workflow_dispatch:
#  pull_request:
#    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Get current commit-hash
        id: commit
        run: echo "::set-output name=git_hash::$(git rev-parse --short '$GITHUB_SHA')"
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build the latest Docker image
        run: |
          docker build . --file work.Dockerfile --tag work-dev
          docker image tag work-dev mattlu/work-dev:latest
          docker image tag work-dev mattlu/work-dev:18.04
          docker image tag work-dev mattlu/work-dev:18.04-${{ steps.commit.outputs.git_hash }}
      - name: Push the latest Docker image
        run: docker push --all-tags mattlu/work-dev
