name: work-dev-18.04

on:
  push:
    paths:
      - 'work.Dockerfile'
#  pull_request:
#    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v1
     - name: Login to DockerHub Registry
       run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
     - name: Build the latest Docker image
       run: |
         docker build . --file work.Dockerfile --tag work-dev
         docker image tag work-dev --tag mattlu/work-dev:latest
         docker image tag work-dev --tag mattlu/work-dev:18.04
     - name: Push the latest Docker image
       run: docker push --all-tags mattlu/work-dev
